trigger:
- main

pool:
  name: 'Default' # Tu agente local en tu PC

variables:
  imageName: 'althira-products'
  dockerRepo: 'yangolas/$(imageName)'

stages:
- stage: Build
  displayName: 'Build and Push'
  jobs:
  - job: Build
    steps:
    # 1. Build y Push a Docker Hub (Esto ya te funcionaba)
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: 'dockerhub-althira'
        repository: '$(dockerRepo)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildId)
          latest

    # 2. Deploy directo usando tu Helm local
    # No necesitamos Service Connection porque el agente usa tu config de K8s
    - powershell: |
        helm upgrade --install althira-products k8s/Charts `
          --values k8s/Charts/values-dev.yaml `
          --set image.tag=$(Build.BuildId) `
          --namespace althira-products
      displayName: 'Deploy con Helm Local'