trigger:
- main

pool:
  name: 'Default'

variables:
  appName: 'althira-products'
  dockerRepo: 'yangolas/$(appName)'
  finalTag: $[ coalesce(variables['tag'], variables['Build.BuildId']) ]

stages:
- stage: Build
  displayName: 'Build and Push'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: 'dockerhub-althira'
        repository: '$(dockerRepo)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildId)
          latest

    - powershell: |
        # 1. Lookin for folder Chart
        $chartPath = Get-ChildItem -Path $(System.DefaultWorkingDirectory) -Filter "Chart.yaml" -Recurse | Select-Object -ExpandProperty DirectoryName -First 1
        cd $chartPath

        # 2. Execute Helm for DEV
        helm upgrade --install $(appName) . `
          --values ./values-dev.yaml `
          --set image.tag=$(finalTag) `
          --namespace $(appName)
      displayName: 'Deploy with Local Helm'