# ---------------------------------------------------------
# ConfigMap
# ---------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: althira-products-config
data:
  # .NET leerá estas variables y sobrescribirá el appsettings.json
  Config__OpenTelemetry__ConnectionString: "#{OpenTelemetry__ConnectionString}#"
  Config__DatabaseRead__ConnectionString: "#{DatabaseRead__ConnectionString}#"
  Config__DatabaseRead__DatabaseName: "#{DatabaseRead__DatabaseName}#"
  Config__DatabaseWrite__ConnectionString: "#{DatabaseWrite__ConnectionString}#"
  Config__MessageBroker__HostName: "#{MessageBroker__HostName}#"
  Config__MessageBroker__UserName: "#{MessageBroker__UserName}#"
  Config__MessageBroker__Password: "#{MessageBroker__Password}#"
  Config__AzureBlobStorage__ConnectionString: "#{AzureBlobStorage__ConnectionString}#"
# ---------------------------------------------------------
# 1. WEB API
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-api
  template:
    metadata:
      labels:
        app: althira-api
    spec:
      containers:
      - name: products-api
        image: yangolas/althira-products:latest
        args: ["webapi"]
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: althira-products-config
# ---------------------------------------------------------
# 2. OUTBOX WORKER
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-outbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-outbox
  template:
    metadata:
      labels:
        app: althira-outbox
    spec:
      containers:
      - name: outbox-worker
        image: yangolas/althira-products:latest
        args: ["outbox"]
        envFrom:
        - configMapRef:
            name: althira-products-config
# ---------------------------------------------------------
# 3. IMAGE WORKER
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-worker-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-image
  template:
    metadata:
      labels:
        app: althira-image
    spec:
      containers:
      - name: image-worker
        image: yangolas/althira-products:latest
        args: ["image"]
        envFrom:
        - configMapRef:
            name: althira-products-config
# ---------------------------------------------------------
# 4. CONSUMER BROKER
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-consumer
  template:
    metadata:
      labels:
        app: althira-consumer
    spec:
      containers:
      - name: consumer-worker
        image: yangolas/althira-products:latest
        args: ["consumer"]
        envFrom:
        - configMapRef:
            name: althira-products-config