# -------------------------------------------------------
# SECRETS
# -------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: althira-products-secrets
  namespace: althira-products
type: Opaque
stringData:
  Config__OpenTelemetry__ConnectionString: "http://otel-collector.althira.svc.cluster.local:4317"
  Config__DatabaseRead__ConnectionString: "mongodb://mongodb-srv.althira.svc.cluster.local:27017"
  Config__DatabaseRead__DatabaseName: "Product"
  Config__DatabaseWrite__ConnectionString: "Server=sqlserver-srv.althira.svc.cluster.local;Database=Product;User Id=sa;Password=TuPasswordSeguro123!;TrustServerCertificate=True;"
  Config__MessageBroker__HostName: "rabbitmq-srv.althira.svc.cluster.local"
  Config__MessageBroker__UserName: "guest"
  Config__MessageBroker__Password: "guest"
  Config__MessageBroker__Port: "5672"
  Config__MessageBroker__ConsumerConcurrency: "1"
  Config__AzureBlobStorage__ConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVERcz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-srv.althira.svc.cluster.local:10000;" 