# -------------------------------------------------------
# CONFIGMAP
# -------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: althira-products-config
  namespace: althira-products
data:
  ASPNETCORE_ENVIRONMENT: "Development"

  # Logs
  Config__Logs__LogLevel: "Information"

  # Outbox Config
  Config__Outbox__BatchSize: "100"
  Config__Outbox__IntervalToPolling: "00:01:00"
  Config__Outbox__RetryPolicy__MaxRetryAttempts: "3"
  Config__Outbox__RetryPolicy__InitialDelay: "00:00:03"
  Config__Outbox__RetryPolicy__BackoffMultiplier: "2"

  # Azure Blob Storage (Metadata del contenedor)
  Config__AzureBlobStorage__ProductImageBlobContainer__WorkerBatchSize: "100"
  Config__AzureBlobStorage__ProductImageBlobContainer__IntervalToPolling: "00:01:00"
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__MaxRetryAttempts: "3"
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__InitialDelay: "00:00:03"
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__BackoffMultiplier: "2"