# -------------------------------------------------------
# OUTBOX WORKER
# -------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-worker-outbox
  namespace: althira-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-products
      component: outbox
  template:
    metadata:
      labels:
        app: althira-products
        component: outbox
    spec:
      initContainers:
      - name: db-migration
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["migration"]
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
      containers:
      - name: outbox
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["outbox"] 
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"