# ---------------------------------------------------------
#  CONSUMER BROKER MESSAGE
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-worker-consumer
  namespace: althira-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: althira-products
      component: consumer
  template:
    metadata:
      labels:
        app: althira-products
        component: consumer
    spec:
      initContainers:
      - name: db-migration
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["migration"]
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
      containers:
      - name: consumer
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["consumer"]
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"