# -------------------------------------------------------
# IMAGE WORKER
# -------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: althira-products-worker-image
  namespace: althira-products
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: althira-products
      component: image-worker
  template:
    metadata:
      labels:
        app: althira-products
        component: image-worker
    spec:
      initContainers:
      - name: db-migration
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["migration"]
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
      containers:
      - name: image-worker
        image: yangolas/althira-products:$(Build.BuildId)
        args: ["image"]
        envFrom:
        - configMapRef:
            name: althira-products-config
        - secretRef:
            name: althira-products-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"