service:
  type: ClusterIP
  port: 80
  
image:
  repository: yangolas/althira-products
  tag: latest # Azure DevOps override this tag within BuildId
  pullPolicy: Always

dbMigration:
  enabled: true

config:
  aspnetEnv: "Development"
  logLevel: "Information"
  webApiHost: "dev.products.althira.com"
  openTelemetry:
    webApiName: "AlthiraProducts.WebApi.Kubernetes"
    consumerBrokerName: "AlthiraProducts.MessageBroker.Consumer.Kubernetes"
    outbox: "AlthiraProducts.Worker.Outbox.Kubernetes"
    storage: "AlthiraProducts.Worker.AzureBlobStorage.Kubernetes"
  cors:
    allowedOrigins: "http://dev.sellers.althira.com"
  outbox:
    batchSize: "100"
    interval: "00:01:00"
    maxRetry: "3"
    initialDelay: "00:00:03"
    backoff: "2"
  blob:
    ingress:
      host: "dev-storage-althira-com"
      port: "80"
    name: "product-images"
    workerBatchSize: "100"
    interval: "00:01:00"
    maxRetry: "3"
    initialDelay: "00:00:03"
    backoff: "2"

components:
  - name: api
    arg: "webapi"
    port: 80
    replicaCount: 1

  - name: worker-consumer
    arg: "consumer"
    replicaCount: 1
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "300m", memory: "512Mi" }

  - name: worker-outbox
    arg: "outbox"
    replicaCount: 1
    resources:
      requests: { cpu: "50m", memory: "128Mi" }
      limits: { cpu: "200m", memory: "256Mi" }

  - name: worker-image
    arg: "image"
    replicaCount: 1
    resources:
      requests: { cpu: "200m", memory: "512Mi" }
      limits: { cpu: "1000m", memory: "1Gi" }