apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetEnv | quote }}
  Config__Logs__LogLevel: {{ .Values.config.logLevel | quote }}
  Config__OpenTelemetry__WebApiName: {{ .Values.config.openTelemetry.webApiName | quote }}
  Config__OpenTelemetry__ConsumerBrokerName: {{ .Values.config.openTelemetry.consumerBrokerName | quote }}
  Config__OpenTelemetry__OutboxWorkerName: {{ .Values.config.openTelemetry.outbox | quote }}
  Config__OpenTelemetry__AzureBlobStorageWorkerName: {{ .Values.config.openTelemetry.storage | quote }}
  Config__OpenTelemetry__AllowedOrigins: {{ .Values.config.cors.allowedOrigins | quote }}
  Config__Outbox__BatchSize: {{ .Values.config.outbox.batchSize | quote }}
  Config__Outbox__IntervalToPolling: {{ .Values.config.outbox.interval | quote }}
  Config__Outbox__RetryPolicy__MaxRetryAttempts: {{ .Values.config.outbox.maxRetry | quote }}
  Config__Outbox__RetryPolicy__InitialDelay: {{ .Values.config.outbox.initialDelay | quote }}
  Config__Outbox__RetryPolicy__BackoffMultiplier: {{ .Values.config.outbox.backoff | quote }}
  Config__AzureBlobStorage__IngressLocalKubernetes__Host: {{ .Values.config.blob.ingress.host | quote }}
  Config__AzureBlobStorage__IngressLocalKubernetes__Port: {{ .Values.config.blob.ingress.port | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__Name: {{ .Values.config.blob.name | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__WorkerBatchSize: {{ .Values.config.blob.workerBatchSize | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__IntervalToPolling: {{ .Values.config.blob.interval | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__MaxRetryAttempts: {{ .Values.config.blob.maxRetry | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__InitialDelay: {{ .Values.config.blob.initialDelay | quote }}
  Config__AzureBlobStorage__ProductImageBlobContainer__RetryPolicy__BackoffMultiplier: {{ .Values.config.blob.backoff | quote }}